name: zKitPvP
version: '${project.version}'
main: it.danilotallaric.zkitpvp.KitPvP
authors: [ Virgili0_ ]
description: KitPvP plugin for Spigot/Paper servers
softdepend: [ PlaceholderAPI, Vault ]
commands:
  kitpvp:
    description: Main command for everything
    aliases: [ kp, zkitpvp ]
  spawn:
    description: Teleport player to spawn
  dropsettings:
    description: Command to manage the pickup settings
    aliases: [ drops, drop-settings ]
  fix:
    description: Fixes inventory
    aliases: [ fixall ]
  giveexp:
    description: Transfer a speciefied amount of levels to another player
    aliases: [ givelevels, expgive, paylevels, payexp ]
  discord:
    description: Discord command
    aliases: [ ds ]
  build:
    description: Build command
  Withdraw:
    description: Withdraw command
    aliases: [ banknote ]
  potion:
    description: Pot command
    aliases: [ pot ]
  zinvsee:
    description: Invsee command
  store:
    description: Store command